apiVersion: 1

datasources:
  - name: trader-db
    uid: trader-sqlite
    type: frser-sqlite-datasource
    access: proxy
    isDefault: true
    jsonData:
      path: /opt/tapewatch/trader.db
    version: 1
    editable: false
